### ISSUE TITLE
unknown tag library error

### ISSUE THREAD

**Issue by virtz** [MoacirSchmidt/dart_mssql#1]
i copied the dart_mssql.dll to the main directory like you said ,but the error still pops up

**Comment by MoacirSchmidt** [comment]
Please update to latest version. 

If the problem persists print the screen showing the error.

**Comment by MoacirSchmidt** [comment]
This project is not suitable for mobile projects. It only runs in Server-Side Dart.

See https://www.dartlang.org/server
