### ISSUE TITLE
Module Could Not Be Found

### ISSUE THREAD

**Issue by mjcouturie** [MoacirSchmidt/dart_mssql#2]
Library Handler Failed despite dart_mssql.dll in project directory, OLE DB Drivers and Visual C++ redistributables installed.

**Comment by mjcouturie** [comment]
0.2.1
Basically using the same example code.
void main() async {
  //starts the connection.
 SqlConnection connection = SqlConnection(host:"centricity-dr", db:"centricityps", user:"HHC\\$SysInfo.userName", password:"");
 String cmd = "select top 10 * From Appointments";

  SqlResult result = connection.execute(cmd,[4]);
  result.rows.forEach((e) {
    print("${e.ApptStart}");
  });
  print("end of printing.");
  connection.close();
  stdin.readLineSync();
}
Thanks for the project.

**Comment by MoacirSchmidt** [comment]
1) Could you please post a print screen containing the exact error message?

2) Are you using Windows Authentication or Active Directory authentication? 

3) Please inform your windows version and SQL SERVER version.

**Comment by MoacirSchmidt** [comment]
Is this a Duplicate of #1 ?

**Comment by mjcouturie** [comment]
No, not a duplicate. Will post responses to your questions tomorrow. Wondering if it was something about switch to 0.2.0 to 0.2.1, as it had been working. Might also have been due to refactoring, but could not get functionality to work in a a new project from scratch. I also rebuilt the dll several times. Anyway will send more information tomorrow. Thanks.

**Comment by mjcouturie** [comment]
"C:\Program Files\Dart\dart-sdk\bin\dart.exe" --enable-asserts --enable-vm-service:59416 C:\Users\mcouturie\WebstormProjects\CentricityQueryTool\lib\centricity_main.dart
Observatory listening on http://127.0.0.1:59416/

lib/centricity_main.dart:1: Warning: Interpreting this as package URI, 'package:CentricityQueryTool/centricity_main.dart'.
The specified module could not be found.
error: library handler failed

Process finished with exit code 254

Windows 10
Windows Authentication
SQL Server 2008 R2 version 10.50.4042

**Comment by MoacirSchmidt** [comment]
This message indicates that some dependency (.dll file) is missing. 

I suggest you to try Dependency Walker (http://www.dependencywalker.com/). Open dart_mssql.dll and see which .dll file is missing.

**Comment by mjcouturie** [comment]
That didn't work, unfortunately. Dependencywalker showed many missing, but turns out it's because it can't walk the tree well. This tool did a better job (https://github.com/lucasg/Dependencies) and showed no dependencies missing. 
![dependencies](https://user-images.githubusercontent.com/7980786/56997689-b0523000-6b76-11e9-8dca-00a948ada62a.png)

**Comment by MoacirSchmidt** [comment]
Yes, you are right! There are no dependency issues with your dart_mssql.dll

I think the last try is uploading a small project that reproduces the problem form me to check!

Could you please do that? Please include your dart_mssql.dll into this project in main project folder!

Thanks!

**Comment by mjcouturie** [comment]
[connectiontester.zip](https://github.com/MoacirSchmidt/dart_mssql/files/3143769/connectiontester.zip)
Thanks for looking at it.

**Comment by mjcouturie** [comment]
Thanks for looking at it.
[testconnection.zip](https://github.com/MoacirSchmidt/dart_mssql/files/3143770/testconnection.zip)

**Comment by MoacirSchmidt** [comment]
I ran your code without any problem:

">F:\DartSdk64\dart-sdk\bin\dart.exe --enable-asserts --enable-vm-service:59416 F:\tests\testconnection\lib\testconnection.dart"

runs ok.

**Comment by mjcouturie** [comment]
Well, at least it's clear the dll works. Is there a specific Visual C++ Redistributable I should be using? Thanks!

**Comment by MoacirSchmidt** [comment]
Did some local tests and I concluded that your problem is definitely NOT RELATED with dll dependencies. 

If the error were related to dll dependencies you would have received an OLE DB ERROR like 80001111 or something when trying to connect do database.

Please copy dart_mssql.dll to all your project folders to make sure it is read corrected.

**Comment by mjcouturie** [comment]
Unfortunately still no luck. I have rebuilt, reinstalled dart, webstorm, etc. The only thing I see different is in your OLEDB client SDK path you have 181 and I have 182. C:\Program Files\Microsoft SQL Server\Client SDK\OLEDB\182\SDK

**Comment by MoacirSchmidt** [comment]
Are you using Dart-Native or Dart-Web? Dart MS-SQL driver only works on Dart-Native

**Comment by mjcouturie** [comment]
I'm not sure what you mean. I downloaded the dart sdk and vm and you see
the code has no web dependencies.  I'll try some more tomorrow.

Thanks.

**Comment by mjcouturie** [comment]
Not sure what the issue was, but when I used WebStorm 2018.2.8 instead of 2019.1.1, everything worked. So, doesn't appear to be an issue with the package or the dll, but something to do with the IDE. Thanks for your help!
