### ISSUE TITLE
I use dart_mssql  in  android project but get these errors?

### ISSUE THREAD

**Issue by mpili1220** [MoacirSchmidt/dart_mssql#3]
has installed ole db and vc++
and copy dart_mssql.dll into path(two path)
**Screenshots**
![dart_mssql_error](https://user-images.githubusercontent.com/17508319/56865122-f1263980-69fc-11e9-9014-58ac26766fa9.jpg)
![Uploading intalled app.jpg…]()
![Uploading 3.jpg…]()

**To Reproduce**
Complete dart code which reproduces the problem:

**Desktop (please complete the following information):**
 - Windows version:Win10 home
 - MS-SQL version:Sql Server2008R2
 - Authentication mode (SQL Server Authentication, Windows Authentication, Active Directory):Mxied mode
 - Version [e.g. 0.2.1]:0.2.1

**Additional context**

**Comment by MoacirSchmidt** [comment]
This project is not suitable for mobile projects. It only runs in Server-Side Dart. 

See https://www.dartlang.org/server

**Comment by MoacirSchmidt** [comment]
Duplicate of #1

**Comment by MoacirSchmidt** [comment]
Duplicate of #1
